# Generated by Django 5.1.5 on 2025-03-03 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='load_time',
            fields=[
                ('object', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('module', models.CharField(blank=True, max_length=255, null=True)),
                ('data_object_type', models.CharField(blank=True, max_length=255, null=True)),
                ('transformation_complexity', models.CharField(blank=True, max_length=255, null=True)),
                ('load_complexity', models.CharField(blank=True, max_length=255, null=True)),
                ('source_complexity', models.CharField(blank=True, max_length=255, null=True)),
                ('scope', models.CharField(blank=True, max_length=255, null=True)),
                ('object_development', models.FloatField(blank=True, null=True)),
                ('iteration_1_data_loading', models.FloatField(blank=True, null=True)),
                ('iteration_1_defects', models.FloatField(blank=True, null=True)),
                ('iteration_2_data_loading', models.FloatField(blank=True, null=True)),
                ('iteration_2_defects', models.FloatField(blank=True, null=True)),
                ('iteration_3_data_loading', models.FloatField(blank=True, null=True)),
                ('iteration_3_defects', models.FloatField(blank=True, null=True)),
                ('production_data_loads', models.FloatField(blank=True, null=True)),
                ('total', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('user_name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='projects',
            fields=[
                ('project_name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('objects_count', models.BigIntegerField(blank=True, default=0, null=True)),
                ('total_efforts', models.FloatField(blank=True, default=0, null=True)),
                ('table_name', models.CharField(blank=True, max_length=255, null=True)),
                ('realize', models.IntegerField(blank=True, null=True)),
                ('live', models.IntegerField(blank=True, null=True)),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_proj', to='api.user')),
            ],
        ),
        migrations.CreateModel(
            name='values',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transformation_complexity', models.CharField(blank=True, max_length=255, null=True)),
                ('load_complexity', models.CharField(blank=True, max_length=255, null=True)),
                ('source_complexity', models.CharField(blank=True, max_length=255, null=True)),
                ('object_development', models.FloatField(blank=True, null=True)),
                ('iteration_1_data_loading', models.FloatField(blank=True, null=True)),
                ('iteration_1_defects', models.FloatField(blank=True, null=True)),
                ('iteration_2_data_loading', models.FloatField(blank=True, null=True)),
                ('iteration_2_defects', models.FloatField(blank=True, null=True)),
                ('iteration_3_data_loading', models.FloatField(blank=True, null=True)),
                ('iteration_3_defects', models.FloatField(blank=True, null=True)),
                ('production_data_loads', models.FloatField(blank=True, null=True)),
                ('total', models.FloatField(blank=True, null=True)),
            ],
            options={
                'unique_together': {('transformation_complexity', 'load_complexity', 'source_complexity')},
            },
        ),
        migrations.CreateModel(
            name='project_efforts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object', models.CharField(max_length=255)),
                ('module', models.CharField(blank=True, max_length=255, null=True)),
                ('data_object_type', models.CharField(blank=True, max_length=255, null=True)),
                ('transformation_complexity', models.CharField(blank=True, max_length=255, null=True)),
                ('load_complexity', models.CharField(blank=True, max_length=255, null=True)),
                ('source_complexity', models.CharField(blank=True, max_length=255, null=True)),
                ('scope', models.CharField(blank=True, max_length=255, null=True)),
                ('object_development', models.FloatField(blank=True, null=True)),
                ('iteration_1_data_loading', models.FloatField(blank=True, null=True)),
                ('iteration_1_defects', models.FloatField(blank=True, null=True)),
                ('iteration_2_data_loading', models.FloatField(blank=True, null=True)),
                ('iteration_2_defects', models.FloatField(blank=True, null=True)),
                ('iteration_3_data_loading', models.FloatField(blank=True, null=True)),
                ('iteration_3_defects', models.FloatField(blank=True, null=True)),
                ('production_data_loads', models.FloatField(blank=True, null=True)),
                ('total', models.FloatField(blank=True, null=True)),
                ('project_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proj_name', to='api.projects')),
            ],
            options={
                'unique_together': {('project_name', 'object')},
            },
        ),
    ]
