# Generated by Django 5.1.5 on 2025-02-18 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='total_efforts',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
