# Generated by Django 5.1.5 on 2025-02-20 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_temp_efforts'),
    ]

    operations = [
        migrations.DeleteModel(
            name='temp_efforts',
        ),
        migrations.AddField(
            model_name='projects',
            name='table_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
