# Generated by Django 5.1.5 on 2025-01-30 12:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connection', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.AutoField(primary_key=True, serialize=False)),
                ('project_name', models.CharField(help_text='...', max_length=255, unique=True, validators=[django.core.validators.RegexValidator(code='...', message='...', regex='^[a-zA-Z][a-zA-Z0-9]*$')])),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='sample',
        ),
    ]
