# Generated by Django 5.1.5 on 2025-01-30 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connection', '0002_project_delete_sample'),
    ]

    operations = [
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connection_name', models.CharField(max_length=255)),
                ('connection_type', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('host', models.CharField(max_length=255)),
                ('sysnr', models.CharField(blank=True, max_length=255, null=True)),
                ('port', models.CharField(max_length=255)),
                ('database', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections', to='connection.project')),
            ],
            options={
                'unique_together': {('project', 'connection_name')},
            },
        ),
    ]
