# Generated by Django 5.1.5 on 2025-01-30 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connection', '0003_connection'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Connection',
        ),
    ]
