# Generated by Django 5.1.5 on 2025-01-30 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connection', '0005_connection'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='connection',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='connection',
            name='project_id',
        ),
    ]
