# Generated by Django 5.1.5 on 2025-01-30 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connection', '0006_alter_connection_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='project_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='connections', to='connection.project'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='connection',
            unique_together={('project_id', 'connection_name')},
        ),
    ]
