# Generated by Django 5.1.5 on 2025-02-03 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connection', '0010_alter_project_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
