# Generated by Django 5.1.5 on 2025-02-04 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connection', '0011_alter_project_project_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='dd02l_desc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
