# Generated by Django 5.1.5 on 2025-02-06 05:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connection', '0012_dd02l_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='objects',
            fields=[
                ('obj_id', models.AutoField(primary_key=True, serialize=False)),
                ('obj_name', models.CharField(blank=True, max_length=255, null=True)),
                ('template_name', models.CharField(blank=True, max_length=255, null=True)),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objects', to='connection.project')),
            ],
            options={
                'unique_together': {('project_id', 'obj_name')},
            },
        ),
    ]
