# Generated by Django 5.1.5 on 2025-02-06 05:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connection', '0013_objects'),
    ]

    operations = [
        migrations.CreateModel(
            name='segments',
            fields=[
                ('segment_id', models.AutoField(primary_key=True, serialize=False)),
                ('segement_name', models.CharField(blank=True, max_length=255, null=True)),
                ('template_name', models.CharField(blank=True, max_length=255, null=True)),
                ('obj_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segement_objid', to='connection.objects')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segement_projid', to='connection.project')),
            ],
        ),
        migrations.CreateModel(
            name='fields',
            fields=[
                ('field_id', models.AutoField(primary_key=True, serialize=False)),
                ('fields', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('isMandatory', models.CharField(blank=True, max_length=255, null=True)),
                ('obj_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields_objid', to='connection.objects')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields_projid', to='connection.project')),
                ('segement_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields_segementid', to='connection.segments')),
            ],
        ),
    ]
