# Generated by Django 5.1.5 on 2025-02-06 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connection', '0014_segments_fields'),
    ]

    operations = [
        migrations.RenameField(
            model_name='segments',
            old_name='template_name',
            new_name='table_name',
        ),
    ]
