# Generated by Django 5.1.5 on 2025-02-06 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connection', '0017_rule_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objects',
            name='project_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objects_project', to='connection.project'),
        ),
    ]
