# Generated by Django 5.1.5 on 2025-02-07 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connection', '0018_alter_objects_project_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='fields',
            name='sap_structure',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
