# Generated by Django 5.1.5 on 2025-02-08 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connection', '0019_fields_sap_structure'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='field_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='rule_fieldId', to='connection.fields'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rule',
            name='obj_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='rule_objid', to='connection.objects'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rule',
            name='project_id',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='rule_projid', to='connection.project'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rule',
            name='segement_id',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='rule_segementid', to='connection.segments'),
            preserve_default=False,
        ),
    ]
