# Generated by Django 5.1.5 on 2025-02-08 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connection', '0020_rule_field_id_rule_obj_id_rule_project_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rule',
            name='Look_Up_Required',
        ),
    ]
