# Generated by Django 5.1.5 on 2025-02-10 05:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connection', '0022_rulesave_delete_rule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rulesave',
            name='version',
        ),
        migrations.CreateModel(
            name='RuleVersion',
            fields=[
                ('Rule_id', models.AutoField(primary_key=True, serialize=False)),
                ('version', models.IntegerField(default=1)),
                ('Source_Table', models.CharField(blank=True, max_length=255, null=True)),
                ('Source_Field_Name', models.CharField(blank=True, max_length=255, null=True)),
                ('Data_Mapping_Rules', models.CharField(blank=True, max_length=255, null=True)),
                ('Target_SAP_Table', models.CharField(blank=True, max_length=255, null=True)),
                ('Target_SAP_Field', models.CharField(blank=True, max_length=255, null=True)),
                ('Text_Description', models.CharField(blank=True, max_length=255, null=True)),
                ('Lookup_Table', models.CharField(blank=True, max_length=255, null=True)),
                ('Last_Updated_By', models.CharField(blank=True, max_length=255, null=True)),
                ('Last_Updated_On', models.DateTimeField(auto_now_add=True)),
                ('Rule_Status', models.CharField(blank=True, max_length=255, null=True)),
                ('Check_Box', models.CharField(blank=True, max_length=255, null=True)),
                ('field_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ruleVersion_fieldId', to='connection.fields')),
                ('obj_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ruleVersion_objid', to='connection.objects')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ruleVersion_projid', to='connection.project')),
                ('segement_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ruleVersion_segementid', to='connection.segments')),
            ],
        ),
    ]
