# Generated by Django 5.1.5 on 2025-02-12 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connection', '0024_remove_ruleversion_field_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saverule',
            name='field_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='connection.fields'),
        ),
    ]
