# Generated by Django 5.1.5 on 2025-02-12 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connection', '0026_alter_rule_field_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='field_id',
            field=models.ForeignKey(default=16158, on_delete=django.db.models.deletion.SET_DEFAULT, to='connection.fields'),
        ),
    ]
