# Generated by Django 5.1.5 on 2025-02-13 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connection', '0027_alter_rule_field_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='data_mapping_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='saverule',
            name='data_mapping_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rule',
            name='field_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='connection.fields'),
        ),
        migrations.AlterField(
            model_name='saverule',
            name='field_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='connection.fields'),
        ),
    ]
