# Generated by Django 5.1.5 on 2025-02-13 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connection', '0028_rule_data_mapping_type_saverule_data_mapping_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='rule_status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='saverule',
            name='rule_status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
