# Generated by Django 5.1.5 on 2025-02-13 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connection', '0029_alter_rule_rule_status_alter_saverule_rule_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rule',
            name='is_latest',
        ),
        migrations.RemoveField(
            model_name='saverule',
            name='is_latest',
        ),
        migrations.AddField(
            model_name='rule',
            name='isMandatory',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='saverule',
            name='isMandatory',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
